### ISSUE TITLE
Help, I Lost My Book in Obsolescence.

### ISSUE THREAD

**Issue by PraseodymiumSpike** [Gamemode4Dev/obsolescence#2]
**Describe the bug**
This isn't really a bug, but it seems like it might have been an oversight. If you lose the Book, is there any way to get it back, or do you just have to restart the Map?

**To Reproduce**
1. Die.
2. Wait 5 minutes.
3. Enjoy!

**Expected behavior**
I would have expected it to have a Tag or something preventing it from Despawning.

**Fix**
There could be a Chest full of these Books at the first Shrine.

**Screenshots**
If applicable, add screenshots to help others understand your problem.

**Environment**
 - Minecraft version: 1.17.1
 - Server version: 1.17.1
 - Installed Datapacks: whatever comes with the Map
 - Installed Mods: none whatsoever

**Additional context**
Sorry, I don't know where else to put this.

**Comment by TheThanathor** [comment]
Hey there! Thanks for the report.

The Guidebook should be an invulnerable item, but it seems that currently doesn't work, we'll push a fix soon but until then you can use this to get a new guidebook:
`/loot give @s loot gm4_guidebook:items/guidebook`

**Comment by BPR02** [comment]
This is not intended; the guidebook is supposed to be invulnerable and never despawn. However, this isn't a game breaking issue, as there are ways to retrieve extra guidebooks. Try to reach the central monument.

**Comment by PraseodymiumSpike** [comment]
Thank you!
